### ISSUE TITLE
Unable to build on macOS /bin/true does not exist

### ISSUE THREAD

**Issue by rhwood** [RobertPHeller/ModelRRSystem#1]
When building on macOS, the configure script sets a number of commands to be ```/bin/true```, however on macOS the path to true is ```/usr/bin/true```. This causes make to fail.

**Comment by RobertPHeller** [comment]
At Sun, 22 Jul 2018 05:13:04 -0700 RobertPHeller/ModelRRSystem <reply@reply.github.com> wrote:

> 
> 
> When building on macOS, the configure script sets a number of commands to be
> ```/bin/true```, however on macOS the path to true is ```/usr/bin/true```.
> This causes make to fail.

Hmm... This really means you are missing some of the programs needed to build. 
The commands set to /bin/true are really needed.  Do you know which these are?

> 

-- 
Robert Heller             -- 978-544-6933
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
heller@deepsoft.com       -- Webhosting Services

**Comment by rhwood** [comment]
The following are set to /bin/true (repeatedly) in Makefiles:

```
BIBTEX = /bin/true
BISONXX = /bin/true
DVIPS = /bin/true
LATEX = /bin/true
MAKEINDEX = /bin/true
PDFLATEX = /bin/true
PS2PDF = /bin/true
```

I have mactex installed into its default location of ```/usr/local/texlive/2018```, but don't see how to tell the configure script to use that directory.

**Comment by rhwood** [comment]
I should mention, I am calling configure as:

```
$ cd ~/Downloads/MRRSystem-2.1.43/
$ ./configure --with-tcl=/usr/local/Cellar/tcl-tk/8.6.8/lib
```

since I am using tcl-tk version 8.6.8 installed using Homebrew.

**Comment by RobertPHeller** [comment]
You need to have these programs in your path.  You only really need bibtex, 
pdflatex, and makeindex.  The TeX system should have these *programs* in 
/usr/local/bin/ or if it has them in someplace like 
/usr/local/texlive/2018/bin, you can make symlinks:

pushd /usr/local/bin
sudo ln -s ../texlive/2018/bin/* ./
popd

and make sure '/usr/local/bin/' is in your path:

PATH=$PATH:/usr/local/bin
export PATH
./configure

bison++ is a *slightly* different issue.  If bison++ is not in your path, the 
build will skip building the XTrakCAD parser (this means it will also skip 
building the Dispatcher [I think]).  

I built bison++ 1.21.8 on my MacMini build box.  I probably should make the 
tarball available.  Or you can "steal" the source from the Ubuntu archives:

http://us.archive.ubuntu.com/ubuntu/pool/universe/b/bison++/bison++_1.21.11.orig
.tar.gz

It should be possible to just download this, extract it, and do a ./configure,
make, and then sudo make install to give you a bison++ exe file in
/usr/local/bin/. This version of bison++ is a pretty vanila C program and
should compile without problems on any POSIX system.

I just pushed an update to configure.in to test for MacOSX and use 
/usr/bin/true for "missing" programs (except for bison++, since that one is 
handled specially by an AutoMake conditional). 

At Sun, 22 Jul 2018 06:05:47 -0700 RobertPHeller/ModelRRSystem <reply@reply.github.com> wrote:

> 
> 
> The following are set to /bin/true (repeatedly) in Makefiles:
> 
> ```
> BIBTEX = /bin/true
> BISONXX = /bin/true
> DVIPS = /bin/true
> LATEX = /bin/true
> MAKEINDEX = /bin/true
> PDFLATEX = /bin/true
> PS2PDF = /bin/true
> ```
> 
> I have mactex installed into its default location of ```/usr/local/texlive/2018```, but don't see how to tell the configure script to use that directory.
> 

-- 
Robert Heller             -- 978-544-6933
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
heller@deepsoft.com       -- Webhosting Services

**Comment by RobertPHeller** [comment]
At Sun, 22 Jul 2018 06:08:12 -0700 RobertPHeller/ModelRRSystem <reply@reply.github.com> wrote:

> 
> 
> I should mention, I am calling configure as:
> 
> ```
> $ cd ~/Downloads/MRRSystem-2.1.43/
> $ ./configure --with-tcl=/usr/local/Cellar/tcl-tk/8.6.8/lib
> ```
> 
> since I am using tcl-tk version 8.6.8 installed using Homebrew.
> 

It is not tested with tcl-tk 8.6, and it is *possible* things will break.

-- 
Robert Heller             -- 978-544-6933
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
heller@deepsoft.com       -- Webhosting Services

**Comment by RobertPHeller** [comment]
Actually, it probably won't build *working* exes using Tcl 8.6, unless you update the tclkit with a newer tclkit.  The one currently in the build tree (trunk/BuildData/tclkit-darwin-univ-aqua is 8.5.17) won't be able to run shared library extensions built with 8.6.  And if you really want to use Tcl 8.6, you'll want to upgrade the Img library, which is 1.4, built against Tcl/Tk 8.5 as well.  Oh, the tclkit-darwin-univ-aqua and the Img library are "universal" binaries: i686/x86_64.  I believe modern Mac binaries are pure x86_64 now.  Some day I need to update things, which means I might need to buy a new/newer MacMini (sigh) or else create a Hackintosh VM or give up providing MacOSX binaries...

**Comment by rhwood** [comment]
If anyone else encounters this, it turns out the real problem was that I did not log out and log back into the mac after installing MacTex, since the installer for MacTex adds a directory to the default path instead of installing symlinks for the various programs listed above.
